CREATE TABLE `event_inquiries` (
	`id` int AUTO_INCREMENT NOT NULL,
	`referenceNumber` varchar(20) NOT NULL,
	`customerName` varchar(255) NOT NULL,
	`phone` varchar(20) NOT NULL,
	`email` varchar(320) NOT NULL,
	`company` varchar(255),
	`eventType` enum('wedding','corporate','school','birthday','private','festival','other') NOT NULL,
	`eventDate` timestamp NOT NULL,
	`eventTime` varchar(20) NOT NULL,
	`venue` text NOT NULL,
	`guestCount` int NOT NULL,
	`serviceType` enum('beverages_only','food_only','both') NOT NULL,
	`preferredBeverages` text,
	`preferredFood` text,
	`budgetRange` varchar(50),
	`specialRequirements` text,
	`referralSource` varchar(50),
	`status` enum('new','contacted','quoted','confirmed','completed','cancelled') NOT NULL DEFAULT 'new',
	`assignedTo` varchar(255),
	`internalNotes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `event_inquiries_id` PRIMARY KEY(`id`),
	CONSTRAINT `event_inquiries_referenceNumber_unique` UNIQUE(`referenceNumber`)
);
--> statement-breakpoint
CREATE TABLE `event_order_items` (
	`id` int AUTO_INCREMENT NOT NULL,
	`eventOrderId` int NOT NULL,
	`itemType` enum('beverage','food','additional_charge') NOT NULL,
	`productId` int,
	`itemName` varchar(255) NOT NULL,
	`quantity` int,
	`unitPrice` int NOT NULL,
	`totalPrice` int NOT NULL,
	`notes` text,
	`chargeType` varchar(50),
	`chargeDescription` text,
	`displayOrder` int NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `event_order_items_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `event_orders` (
	`id` int AUTO_INCREMENT NOT NULL,
	`orderNumber` varchar(20) NOT NULL,
	`inquiryId` int,
	`customerName` varchar(255) NOT NULL,
	`phone` varchar(20) NOT NULL,
	`email` varchar(320) NOT NULL,
	`company` varchar(255),
	`eventType` varchar(50),
	`eventDate` timestamp NOT NULL,
	`eventTime` varchar(20) NOT NULL,
	`venue` text NOT NULL,
	`guestCount` int NOT NULL,
	`beveragesSubtotal` int NOT NULL DEFAULT 0,
	`foodSubtotal` int NOT NULL DEFAULT 0,
	`additionalChargesSubtotal` int NOT NULL DEFAULT 0,
	`subtotal` int NOT NULL DEFAULT 0,
	`gstAmount` int NOT NULL DEFAULT 0,
	`discountAmount` int NOT NULL DEFAULT 0,
	`discountType` enum('percentage','fixed'),
	`discountReason` varchar(255),
	`grandTotal` int NOT NULL,
	`advancePercentage` int NOT NULL DEFAULT 50,
	`advanceAmount` int,
	`advancePaid` boolean NOT NULL DEFAULT false,
	`advancePaidAt` timestamp,
	`advancePaymentMethod` varchar(50),
	`balanceAmount` int,
	`balancePaid` boolean NOT NULL DEFAULT false,
	`balancePaidAt` timestamp,
	`balancePaymentMethod` varchar(50),
	`eventOrderStatus` enum('draft','quoted','confirmed','in_progress','completed','cancelled') NOT NULL DEFAULT 'draft',
	`quoteSentAt` timestamp,
	`confirmedAt` timestamp,
	`internalNotes` text,
	`createdBy` varchar(255),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `event_orders_id` PRIMARY KEY(`id`),
	CONSTRAINT `event_orders_orderNumber_unique` UNIQUE(`orderNumber`)
);
--> statement-breakpoint
CREATE TABLE `workshop_bookings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`bookingNumber` varchar(20) NOT NULL,
	`workshopId` int NOT NULL,
	`userId` int,
	`name` varchar(255) NOT NULL,
	`email` varchar(320) NOT NULL,
	`phone` varchar(20) NOT NULL,
	`ticketsBooked` int NOT NULL,
	`totalAmount` int NOT NULL,
	`paymentStatus` enum('pending','completed','failed','refunded') NOT NULL DEFAULT 'pending',
	`paymentMethod` varchar(50),
	`razorpayOrderId` varchar(100),
	`razorpayPaymentId` varchar(100),
	`bookingStatus` enum('confirmed','cancelled','attended','no_show') NOT NULL DEFAULT 'confirmed',
	`specialRequirements` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `workshop_bookings_id` PRIMARY KEY(`id`),
	CONSTRAINT `workshop_bookings_bookingNumber_unique` UNIQUE(`bookingNumber`)
);
--> statement-breakpoint
CREATE TABLE `workshops` (
	`id` int AUTO_INCREMENT NOT NULL,
	`slug` varchar(100) NOT NULL,
	`title` varchar(255) NOT NULL,
	`description` text,
	`instructor` varchar(255) NOT NULL,
	`instructorTitle` varchar(100),
	`instructorImage` varchar(500),
	`workshopDate` timestamp NOT NULL,
	`duration` varchar(50) NOT NULL,
	`location` varchar(255) NOT NULL,
	`maxCapacity` int NOT NULL,
	`ticketsSold` int NOT NULL DEFAULT 0,
	`ticketPrice` int NOT NULL,
	`imageUrl` varchar(500),
	`highlights` text,
	`whatYouLearn` text,
	`includes` text,
	`workshopStatus` enum('upcoming','ongoing','completed','cancelled') NOT NULL DEFAULT 'upcoming',
	`isActive` boolean NOT NULL DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `workshops_id` PRIMARY KEY(`id`),
	CONSTRAINT `workshops_slug_unique` UNIQUE(`slug`)
);
