CREATE TABLE `event_inquiries` (
	`id` int AUTO_INCREMENT NOT NULL,
	`customerName` varchar(200) NOT NULL,
	`customerEmail` varchar(320) NOT NULL,
	`customerPhone` varchar(20) NOT NULL,
	`companyName` varchar(200),
	`eventType` enum('wedding','corporate','school','private','other') NOT NULL,
	`eventDate` timestamp NOT NULL,
	`eventTime` varchar(50),
	`venue` text NOT NULL,
	`guestCount` int NOT NULL,
	`cateringType` enum('beverages_only','food_only','both') NOT NULL,
	`preferredItems` text,
	`budgetRange` varchar(100),
	`specialRequirements` text,
	`status` enum('new','contacted','quoted','confirmed','declined','completed') NOT NULL DEFAULT 'new',
	`adminNotes` text,
	`assignedTo` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `event_inquiries_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `event_order_items` (
	`id` int AUTO_INCREMENT NOT NULL,
	`eventOrderId` int NOT NULL,
	`itemType` enum('beverage','food','staff','delivery','equipment','other') NOT NULL,
	`itemName` varchar(200) NOT NULL,
	`description` text,
	`quantity` int NOT NULL DEFAULT 1,
	`unitPrice` int NOT NULL,
	`totalPrice` int NOT NULL,
	`staffCount` int,
	`hoursWorked` decimal(4,1),
	`hourlyRate` int,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `event_order_items_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `event_orders` (
	`id` int AUTO_INCREMENT NOT NULL,
	`eventNumber` varchar(20) NOT NULL,
	`inquiryId` int,
	`customerName` varchar(200) NOT NULL,
	`customerEmail` varchar(320) NOT NULL,
	`customerPhone` varchar(20) NOT NULL,
	`companyName` varchar(200),
	`eventType` enum('wedding','corporate','school','private','other') NOT NULL,
	`eventDate` timestamp NOT NULL,
	`eventTime` varchar(50),
	`venue` text NOT NULL,
	`guestCount` int NOT NULL,
	`subtotal` int NOT NULL DEFAULT 0,
	`discountAmount` int NOT NULL DEFAULT 0,
	`discountReason` text,
	`sgst` int NOT NULL DEFAULT 0,
	`cgst` int NOT NULL DEFAULT 0,
	`totalAmount` int NOT NULL DEFAULT 0,
	`advancePercentage` int NOT NULL DEFAULT 50,
	`advanceAmount` int NOT NULL DEFAULT 0,
	`advancePaid` boolean NOT NULL DEFAULT false,
	`advancePaidAt` timestamp,
	`balanceAmount` int NOT NULL DEFAULT 0,
	`balancePaid` boolean NOT NULL DEFAULT false,
	`balancePaidAt` timestamp,
	`status` enum('draft','quoted','confirmed','in_progress','completed','cancelled') NOT NULL DEFAULT 'draft',
	`internalNotes` text,
	`customerNotes` text,
	`createdBy` int NOT NULL,
	`createdByName` varchar(200),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `event_orders_id` PRIMARY KEY(`id`),
	CONSTRAINT `event_orders_eventNumber_unique` UNIQUE(`eventNumber`)
);
--> statement-breakpoint
CREATE TABLE `workshop_bookings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`bookingNumber` varchar(20) NOT NULL,
	`workshopId` int NOT NULL,
	`userId` int,
	`customerName` varchar(200) NOT NULL,
	`customerEmail` varchar(320) NOT NULL,
	`customerPhone` varchar(20) NOT NULL,
	`ticketCount` int NOT NULL DEFAULT 1,
	`attendeeNames` text,
	`unitPrice` int NOT NULL,
	`totalAmount` int NOT NULL,
	`paymentStatus` enum('pending','completed','failed','refunded') NOT NULL DEFAULT 'pending',
	`paymentMethod` enum('razorpay','cash'),
	`razorpayOrderId` varchar(100),
	`razorpayPaymentId` varchar(100),
	`paidAt` timestamp,
	`status` enum('pending','confirmed','cancelled','attended','no_show') NOT NULL DEFAULT 'pending',
	`specialRequirements` text,
	`adminNotes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `workshop_bookings_id` PRIMARY KEY(`id`),
	CONSTRAINT `workshop_bookings_bookingNumber_unique` UNIQUE(`bookingNumber`)
);
--> statement-breakpoint
CREATE TABLE `workshops` (
	`id` int AUTO_INCREMENT NOT NULL,
	`title` varchar(200) NOT NULL,
	`slug` varchar(200) NOT NULL,
	`description` text NOT NULL,
	`shortDescription` varchar(500),
	`imageUrl` text,
	`galleryImages` text,
	`workshopDate` timestamp NOT NULL,
	`startTime` varchar(20) NOT NULL,
	`endTime` varchar(20) NOT NULL,
	`duration` varchar(50),
	`venue` text NOT NULL,
	`venueAddress` text,
	`totalCapacity` int NOT NULL,
	`bookedCount` int NOT NULL DEFAULT 0,
	`price` int NOT NULL,
	`earlyBirdPrice` int,
	`earlyBirdDeadline` timestamp,
	`instructorName` varchar(200) NOT NULL,
	`instructorBio` text,
	`instructorImage` text,
	`includes` text,
	`status` enum('draft','published','cancelled','completed') NOT NULL DEFAULT 'draft',
	`isFeatured` boolean NOT NULL DEFAULT false,
	`metaTitle` varchar(200),
	`metaDescription` varchar(500),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `workshops_id` PRIMARY KEY(`id`),
	CONSTRAINT `workshops_slug_unique` UNIQUE(`slug`)
);
